---
title: "Trabajo#3"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, include = FALSE)
```

### Paquetes
```{r paquetes, message=FALSE, warning=FALSE}
library(dplyr)
library(sf)
library(DT)
library(plotly)
library(leaflet)
library(raster)
library(spData)
```

### Carga de Datos

```{r carga de Datos, message=FALSE, warning=FALSE}
especies_primates <-
  st_read("https://raw.githubusercontent.com/gf0604-procesamientodatosgeograficos/2021i-datos/main/gbif/primates-cr-registros.csv",
          options = c (
            "X_POSSIBLE_NAMES=decimalLongitude",
            "Y_POSSIBLE_NAMES=decimalLatitude",
            quiet = TRUE
          )
  )

st_crs(especies_primates) = 4326

cantones <-
  st_read(
    "https://raw.githubusercontent.com/gf0604-procesamientodatosgeograficos/2021i-datos/main/ign/delimitacion-territorial-administrativa/cr_cantones_simp_wgs84.geojson",
    quiet = TRUE
  )
provincias <-
  st_read(
    "https://raw.githubusercontent.com/gf0604-procesamientodatosgeograficos/2021i-datos/main/ign/delimitacion-territorial-administrativa/cr_provincias_simp_wgs84.geojson",
    quiet = TRUE
  )



cantones <-
  especies_primates %>%
  st_join(cantones["canton"])
```
# Tabla para cada registro
```{r tabla para cada registro, message=FALSE, warning=FALSE}
especies_primates %>%
  st_drop_geometry() %>%
  dplyr::select(family, species, stateProvince, locality, eventDate) %>%
  datatable(
    colnames = c("Provincia", "Especie", "Provincia", "Cantones", "Fecha"),
    options = list(
      searchHighlight = TRUE,
      language = list(url = "//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json")
    )
  )
```

## Especies

```{r especies, message=FALSE, warning=FALSE}
 aullador <-
  especies_primates %>% dplyr::select(family, species, stateProvince, locality, eventDate) %>%
  filter(species == "Alouatta palliata")
 carablanca <-
  especies_primates %>% dplyr::select(family, species, stateProvince, locality, eventDate) %>%
  filter(species == "Cebus capucinus")
 araña <-
  especies_primates %>% dplyr::select(family, species, stateProvince, locality, eventDate) %>%
  filter(species == "Ateles geoffroyi")
 ardilla <-
  especies_primates %>% dplyr::select(family, species, stateProvince, locality, eventDate) %>%
  filter(species == "Saimiri oerstedii")

```

# Gráfico Pastel

```{r Grafico pastel, message=FALSE, warning=FALSE}
especies_primates %>%
  plot_ly(
    labels = ~c("Mono aullador","Mono araña","Mono ardillla","Mono carablanca"
    ),
    values = ~c(1994, 599, 453, 1463),
    
    type = "pie")%>%
  config(locale = "es")%>%
  layout(
    title = "",
    xaxis = list(showgrid = FALSE,zeroline = FALSE,showticklabels = FALSE
    ),
    yaxis = list( showgrid = FALSE,zeroline = FALSE, showticklabels = FALSE
    )
  )

```

### Data Altitud

```{r Data Altitud, message=FALSE, warning=FALSE}
alt <- getData(
  "worldclim",
  var = "alt",
  res = .5,
  lon = -84,
  lat = 10
)

altitud <-alt %>% crop(provincias) %>% mask(provincias)
col <- colorNumeric(c("red", "#FF0000", "#FF3333"),
                    values(altitud),
                    na.color = "transparent")
```

### Especies

```{r especies, message=FALSE, warning=FALSE}
Ateles <- paste0((araña$species),
                 
                 (araña$provincia),
                 
                 (araña$locality),
                 
                 (araña$eventDate)
)

Saimiri <- paste0((ardilla$species),
                  
                  (ardilla$provincia),
                  
                  (ardilla$locality),
                  
                  (ardilla$eventDate)
)

Cebus <- paste0((carablanca$species),
                (carablanca$provincia),
                (carablanca$locality),
                (carablanca$eventDate)
)

Alouatta <- paste0((aullador$species),
                   (aullador$provincia),
                   (aullador$locality),
                   (aullador$eventDate)
)
```

# Mapa

```{r mapa, message=FALSE, warning=FALSE}
especies_primates %>%
  leaflet() %>%
  addProviderTiles(providers$OpenStreetMap.Mapnik, group = "OpenStreetMap") %>%
  addProviderTiles(providers$Stamen.TonerLite, group = "Stamen Toner Lite") %>%
  addProviderTiles(providers$Esri.WorldImagery, group = "Imágenes de ESRI") %>%
  addRasterImage(
    altitud, 
    colors = col, 
    opacity = 0.8,
    group = "Altitud") %>%
  addCircleMarkers(
    data = aullador,
    stroke = F,
    radius = 4,
    fillColor = "#CC6633",
    fillOpacity = 1,
    popup = Alouatta ,
    group = "Alouatta palliata"
  ) %>%
  addCircleMarkers(
    data = ardilla,
    stroke = F,
    radius = 4,
    fillColor = "red",
    fillOpacity = 1,
    popup = Saimiri,
    group = "Saimiri oerstedii"
  ) %>%
  addCircleMarkers(
    data = araña,
    stroke = F,
    radius = 4,
    fillColor = "#9933FF",
    fillOpacity = 1,
    popup = Ateles,
    group = "Ateles geoffroyi"
  ) %>%
  addCircleMarkers(
    data = carablanca,
    stroke = F,
    radius = 4,
    fillColor = "#FFFF00",
    fillOpacity = 1,
    popup = Cebus,
    group = "Cebus capucinus"
  ) %>%
  addLayersControl(
    baseGroups = c("OpenStreetMap", "Stamen Toner Lite", 
                   "Imágenes de ESRI"),
    overlayGroups = c("Alouatta palliata", "Cebus capucinus", 
                      "Ateles geoffroyi", "Saimiri oerstedii"
                      ,"Altitud")
  ) %>%
  addMiniMap(tiles = providers$Stamen.OpenStreetMap.Mapnik,
             position = "bottomleft",
             toggleDisplay = TRUE
  )

```







